server:
  port: 8803
spring:
  datasource:
    sys:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring-boot-demo?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password:
    fin:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring-boot-demo-backup?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password:

# mybatis映射文件路径
mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml